In [2]:
import numpy as np 

# Create array

In [4]:
# create array
np.array([1,2,3,4])
# array with performance
np.array([1,2,3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

# Dimension and shape

In [32]:
A = np.array([[1,2,3],
             [4,5,6]])


In [12]:
# Get num of row and col
# A.shape
np.shape(A)

(2, 3)

In [14]:
# get dimens
# A.ndim
np.ndim(A)

2

In [15]:
# get size
# A.size
np.size(A)

6

In [27]:
B = np.array([
    [
        [45,12,4],
        [7,2,7]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,24,3],
        [4,5,6]
    ],
    [
        [1,24,3],
        [4,5,6]
    ]
])

In [28]:
B.shape

(4, 2, 3)

In [29]:
B.ndim

3

In [30]:
B.size

24

# Indexing and Slicing Matrix

In [33]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
A[1]

array([4, 5, 6])

In [35]:
A[1][1]

5

In [38]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A[2,1]

8

In [37]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [43]:
# Modify row
A[1] = np.array([10,110,10])
A

array([[  1,   2,   3],
       [ 10, 110,  10],
       [  7,   8,   9]])

In [45]:
A[2]=9
A

array([[  1,   2,   3],
       [ 10, 110,  10],
       [  9,   9,   9]])

# Summary Statistics

In [46]:
# Summary Statistics
a = np.array([1,2,3,4])

In [48]:
np.sum(a)

10

In [49]:
# Compute the arithmetic mean along the specified axis. (trung binh)
np.mean(a)

2.5

In [50]:
# Compute the standard deviation along the specified axis. (do lech chuan)
np.std(a)

1.118033988749895

In [51]:
# Compute the variance along the specified axis. (phuong sai)
np.var(a)

1.25

In [52]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [55]:
# calculate by rows
np.sum(A, axis=0) 

array([12, 15, 18])

In [56]:
# calculate by cols
np.sum(A, axis=1)

array([ 6, 15, 24])

In [54]:
np.mean(A, axis=0)

array([4., 5., 6.])

# Broadcasting and Vectorized operations

In [59]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [60]:
a + 10

array([10, 11, 12, 13])

In [63]:
a*10

array([ 0, 10, 20, 30])

In [69]:
a = np.arange(4)
a+=5
a

array([5, 6, 7, 8])

In [ ]:
l = [0,1,2,3]

# Bool arrays

In [71]:
a = np.arange(4)

In [77]:
k = a[[0,-2]]
k

array([0, 2])

In [74]:
a[[True, True, False, True]]

array([0, 1, 3])

In [78]:
# check the element with cond
a >=2

array([False, False,  True,  True])

In [79]:
# show element with cond
a[a>=2]

array([2, 3])

In [80]:
# multi cond
a[(a<=2) & (a%2==0)]

array([0, 2])

In [82]:
A = np.random.randint(100, size=(3,3))
A

array([[ 2, 49, 20],
       [92, 35, 76],
       [ 9, 25, 30]])

# Performance and memory

In [84]:
import sys

sys.getsizeof(1)

28

In [88]:
np.dtype(np.int8).itemsize

1

In [114]:
l = list(range(10000))

In [115]:
a = np.arange(10000)

In [118]:
%time np.sum(a**2)

CPU times: user 0 ns, sys: 78 µs, total: 78 µs
Wall time: 75.1 µs


333283335000

In [119]:
%time sum(x**2 for x in l)

CPU times: user 1.43 ms, sys: 278 µs, total: 1.71 ms
Wall time: 1.71 ms


333283335000